[metadata]
name = PerturbDecodeMulti
version = 0.1.0
description = A Python package with R integration and PyTorch models
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/yourusername/PerturbDecodeMulti
author = Basak Eraslan
author_email = basak.eraslan1@gmail.com
license = MIT
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    License :: OSI Approved :: MIT License

[options]
packages = find:
python_requires = >=3.8
