# Parameters
projectDir="/home/eraslab1/Projects/E3Ligase/analysisSingle"
anndataFileName="outputs/anndata/adata-hash-features_singlets_05232020.h5ad"
anndataFileName2="outputs/anndata/adata-hash-features_singlets_05242020.h5ad"

par_species = "mouse"
par_data_dir = "data"
par_initial_umi_cutoff = 1000
par_initial_gene_cutoff = 300
par_empty_drops_lower_umi_cutoff = 200
par_empty_drops_ignore_cutoff = 10
par_empty_drops_niters = 10000
par_empty_drops_fdr_cutoff = 0.01
par_empty_drops_retain = 1000
par_cutoff_min_counts = 1000
par_cutoff_min_genes = 300
par_cutoff_min_cells = 400
par_cutoff_max_genes = None
par_final_empty_drops_fdr_cutoff = 0.01
par_remove_mito_genes = True
par_mito_cutoff = 0.15
par_remove_sex_genes = False
par_preprocessing_target_sum = 10000
par_regress_out_variables = []
par_regress_out_n_jobs = 6
par_downstream_n_top_genes = 2000
par_downstream_hvg_batch_key = None
par_downstream_n_pcs = 50
par_downstream_n_neighbors = 15
par_downstream_louvain_resolution = 1
par_downstream_neighbor_metric = "euclidean"
par_save_filename_sample = "outputs/anndata/adata-sample-%s.h5ad"
par_save_filename_1 = "outputs/anndata/adata.h5ad"
par_save_filename_2 = "outputs/anndata/adata_singlets.h5ad"
par_save_filename_3 = "outputs/anndata/adata_singlets.h5ad"
par_save_filename_group = "outputs/anndata/adata-group-%s.h5ad"
par_remove_doublets = True
par_generate_plots_per_group = True
par_group_key = "round"
par_merge_type = "outer"
par_batch_key = "sample_name"
par_de_group = "leiden"
par_de_n_genes = 2000
par_de_method = "t-test_overestim_var"
par_per_group_de = True
par_save_filename_de = "outputs/reports/de-genes.xlsx"
par_save_filename_de_group = "outputs/reports/de-genes-%s.xlsx"
